In [25]:
import numpy as np
a = np.array([[3.25,7.19,8.66,7.36],
              [9.35,7.26,4.76,7.61],
              [1.75,5.14,3.60,7.88],
              [5.45,6.29,3.22,7.19]])
print (a.shape)
print (a.ndim)
print (a.size)
print (len(a))
print (a)
a[2,2]
a[2,:]
a[:,1]
a.reshape(8,2)
print(a.min())
print(a.max())
print(a.sum())
print(a.min(0))
print(a.min(1))
b=a.reshape(1,16)
print(b)
b.argmax()
b.argmin()
print(b.argmin())
print(a.argmax(0))
print(a.argmax(1))
a.ndim
c=a.reshape(-1)
c
c.ndim
d=a.reshape(-1,1)
d







(4, 4)
2
16
4
[[3.25 7.19 8.66 7.36]
 [9.35 7.26 4.76 7.61]
 [1.75 5.14 3.6  7.88]
 [5.45 6.29 3.22 7.19]]
1.75
9.35
95.96000000000001
[1.75 5.14 3.22 7.19]
[3.25 4.76 1.75 3.22]
[[3.25 7.19 8.66 7.36 9.35 7.26 4.76 7.61 1.75 5.14 3.6  7.88 5.45 6.29
  3.22 7.19]]
8
[1 1 0 2]
[2 0 3 3]


array([[3.25],
       [7.19],
       [8.66],
       [7.36],
       [9.35],
       [7.26],
       [4.76],
       [7.61],
       [1.75],
       [5.14],
       [3.6 ],
       [7.88],
       [5.45],
       [6.29],
       [3.22],
       [7.19]])